server:
  port: 8761  # 포트번호
spring:
  application:
    name: eureka-service
eureka:
  client:
    register-with-eureka: false # 해당 서버를 유레카에 등록하겠다
    fetch-registry: false # 해당 서버가 다른 서비스의 endpoints에 대한 정보 다운을 위해 Eureka서버에 연결을 시도 할 건가